# Site configuration

title: 'Fine Arts Museums of San Francisco Digital Stories'
url: ''
# uncomment below for prod verion.
# url: 'http://digitalstories.famsf.org/early-monet/'

# Uncomment below for FAMSF staging.
# url: 'digitalstories.internal.famsf.org'

# Uncomment below for github pages.
# url: 'https://palantirnet.github.io/famsf-digital-stories'

text_extensions: [ 'htm', 'html', 'html.twig', 'twig.html', 'js', 'less', 'markdown', 'md', 'mkd', 'mkdn', 'coffee', 'css', 'erb', 'haml', 'handlebars', 'hb', 'ms', 'mustache', 'php', 'rb', 'sass', 'scss', 'slim', 'txt', 'xhtml', 'xml', 'svg' ]

server_watch_ext: ['html', 'htm', 'xml', 'css', 'js', 'twig', 'md', 'svg']

collections:
  elements:
    output: true
    title: "Elements"
    sort_by: title
    sort_type: 'ascending'

  components:
    output: true
    title: "Components"
    sort_by: title
    sort_type: 'ascending'

  comps:
    output: true
    title: "High Fidelity Comps"
    sort_by: title
    sort_type: 'ascending'

  templates:
    output: true
    title: "Templates"
    sort_by: title
    sort_type: 'ascending'
